/**
 * ============================================================
 *  THEKKAN PORE SILAMBA KALAI — BRANCH DATA
 * ============================================================
 *
 *  type: "main"    → Original 3 branches run by the masters
 *  type: "student" → New branches opened by students
 *                    Must include: trainedUnder (master name)
 *
 *  HOW TO ADD A MAIN BRANCH:
 *    Shouldn't need to — only 3 main branches exist.
 *
 *  HOW TO ADD A STUDENT BRANCH:
 *    1. Use branch-manager.html to fill in the details
 *    2. Paste the generated entry into BRANCHES below
 *    3. Save pages/branchN.html (generated by the tool)
 *    4. Add master image to images/ folder
 *    That's it — all pages update automatically.
 * ============================================================
 */

const BRANCHES = [

  // ── MAIN BRANCHES (original 3) ──────────────────────────
  {
    id: 1,
    type: "main",
    file: "branch1.html",
    name: "Otteri Extn Branch",
    location: "Otteri Extn, Chennai",
    masters: [
      { name: "Thamim Ansari S", image: "master1.jpg", role: "Chief Instructor" },
      { name: "Jaipoon Nisha S", image: "master2.jpg", role: "Chief Instructor" }
    ],
    phone: ["+91 9677210757", "+91 7299947188"],
    email: ["thekkanporesilambakalai01@gmail.com", "thekkanporesilambakalai02@gmail.com"],
    schedule: "SAT: 6AM – 7:30AM · SUN: 7AM – 9+AM",
    instagram: "thekkanporesilambam_otteri",
    about: "Two masters, one tradition. Chief instructors and founders of Otteri Extn Branch, dedicated to preserving ancient silambam forms."
  },
  {
    id: 2,
    type: "main",
    file: "branch2.html",
    name: "Karasangal Branch",
    location: "Karasangal, Chennai",
    masters: [
      { name: "Rasool Mohideen M", image: "master3.jpg", role: "Chief Instructor" }
    ],
    phone: ["+91 9445903440"],
    email: ["thekkanporesilambakalai03@gmail.com"],
    schedule: "SAT: 6:30AM – 8AM · SUN: 6:30AM – 8AM",
    instagram: "thekkanporesilambam_karasangal",
    about: "Specialises in competitive silambam, producing state-level champions year after year."
  },
  {
    id: 3,
    type: "main",
    file: "branch3.html",
    name: "Vanchuvanchery Branch",
    location: "Vanchuvanchery, Chennai",
    masters: [
      { name: "Lakshmanan A", image: "master4.jpg", role: "Chief Instructor" }
    ],
    phone: ["+91 9094942226"],
    email: ["thekkanporesilambakalai04@gmail.com"],
    schedule: "SAT: 6AM – 7:30AM · SUN: 6AM – 7:30AM",
    instagram: "tpsk_vanchuvanchery",
    about: "Focuses on youth development and cultural education through the martial art form."
  },

  // ── STUDENT BRANCHES — ADD NEW ONES BELOW ───────────────
  // Copy this template and fill in the details:
  //
  // ,{
  //   id: 4,
  //   type: "student",
  //   file: "branch4.html",
  //   name: "New Branch Name",
  //   location: "Area, Chennai",
  //   trainedUnder: "Thamim Ansari S",   ← which master trained this instructor
  //   masters: [
  //     { name: "Instructor Name", image: "master5.jpg", role: "Instructor" }
  //   ],
  //   phone: ["+91 XXXXXXXXXX"],
  //   email: ["email@gmail.com"],
  //   schedule: "SAT & SUN: 6AM – 8AM",
  //   instagram: "instagram_handle",
  //   about: "Brief description of this branch."
  // }

];

/* ── Computed helpers ─────────────────────────────────── */
const MAIN_BRANCHES    = BRANCHES.filter(b => b.type === "main");
const STUDENT_BRANCHES = BRANCHES.filter(b => b.type === "student");

function getTotalMasters() {
  return BRANCHES.reduce((sum, b) => sum + b.masters.length, 0);
}

/* ── Injectors ────────────────────────────────────────── */
function injectBranchCount() {
  const el = document.getElementById('branchCount');
  if (el) el.textContent = BRANCHES.length;
}
function injectMasterCount() {
  const el = document.getElementById('masterCount');
  if (el) el.textContent = getTotalMasters();
}

/* ── Footer branch list ───────────────────────────────── */
function buildFooterBranches(basePath = '') {
  const ul = document.getElementById('footerBranchList');
  if (!ul) return;
  ul.innerHTML = BRANCHES.map(b =>
    `<li><a href="${basePath}${b.file}">${b.name}</a></li>`
  ).join('');
}

/* ── Single location card HTML ────────────────────────── */
function _locationCardHTML(b, basePath, isStudent) {
  const masterNames = b.masters.map(m => m.name).join(' & ');
  const mastersLabel = b.masters.length > 1
    ? `<span style="font-size:12px;color:var(--text-muted);font-family:'Raleway',sans-serif;font-weight:300;"> — ${b.masters.length} Instructors</span>`
    : '';
  const phones = b.phone.map(p =>
    `<a href="tel:${p.replace(/\s/g,'')}">${p}</a>`
  ).join('  ·  ');
  const emails = b.email.map(e =>
    `<a href="mailto:${e}">${e}</a>`
  ).join('<br>');
  const trainedTag = isStudent && b.trainedUnder
    ? `<span class="trained-tag">🎓 Trained under ${b.trainedUnder}</span>`
    : '';
  return `
    <div class="location-card${isStudent ? ' student-branch' : ''} scroll-reveal">
      <h3>${b.name}${mastersLabel}</h3>
      ${trainedTag}
      <p class="loc-master">${masterNames}</p>
      <p>📍 ${b.location}</p>
      <p>📞 ${phones}</p>
      <p>📧 ${emails}</p>
      <p>🕐 ${b.schedule}</p>
      <div style="margin-top:16px;">
        <a href="${basePath}${b.file}" class="view-branch-link" style="font-size:11px;letter-spacing:2px;color:var(--gold);text-transform:uppercase;border:1px solid var(--border);padding:8px 16px;transition:var(--transition);">View Branch →</a>
      </div>
    </div>`;
}

/* ── Contact page: main branches grid ─────────────────── */
function buildLocationCards(basePath = '') {
  const grid = document.getElementById('locationsGrid');
  if (!grid) return;
  grid.innerHTML = MAIN_BRANCHES.map(b => _locationCardHTML(b, basePath, false)).join('');
}

/* ── Contact page: student branches grid ──────────────── */
function buildStudentLocationCards(basePath = '') {
  const grid = document.getElementById('studentLocationsGrid');
  if (!grid) return;
  if (STUDENT_BRANCHES.length === 0) {
    grid.closest('.student-contact-section')?.style.setProperty('display', 'none');
    return;
  }
  grid.innerHTML = STUDENT_BRANCHES.map(b => _locationCardHTML(b, basePath, true)).join('');
}

/* ── Master directory table ───────────────────────────── */
function buildMasterTable() {
  const tbody = document.getElementById('masterTableBody');
  if (!tbody) return;
  tbody.innerHTML = BRANCHES.flatMap(b =>
    b.masters.map(m => `
      <tr style="border-bottom:1px solid var(--border);">
        <td style="padding:16px 20px;color:var(--text);font-size:14px;">${m.name}</td>
        <td style="padding:16px 20px;color:var(--text-muted);font-size:13px;">
          ${b.name}
          ${b.type === 'student' ? '<span style="font-size:10px;color:#666;margin-left:6px;letter-spacing:1px;">STUDENT BRANCH</span>' : ''}
        </td>
        <td style="padding:16px 20px;">
          ${b.phone.map(p => `<a href="tel:${p.replace(/\s/g,'')}" style="color:var(--gold);font-size:13px;display:block;">${p}</a>`).join('')}
        </td>
        <td style="padding:16px 20px;">
          <a href="https://instagram.com/${b.instagram}" target="_blank" style="color:var(--gold);font-size:13px;">@${b.instagram}</a>
        </td>
      </tr>`)
  ).join('');
}

/* ── Home page: main masters grid ─────────────────────── */
function buildMastersGrid() {
  const grid = document.getElementById('mastersGrid');
  if (!grid) return;
  grid.innerHTML = MAIN_BRANCHES.map(b => {
    const isDouble = b.masters.length > 1;
    if (isDouble) {
      return `
        <div class="master-card branch1-double" onclick="window.location='pages/${b.file}'" data-branch="${b.id}">
          <div class="card-glow"></div>
          <div class="double-img-row">
            ${b.masters.map(m => `
              <div class="double-img-wrap">
                <img src="images/${m.image}" alt="${m.name}" onerror="this.src='images/placeholder.jpg'" />
                <div class="double-name">${m.name}</div>
              </div>`).join('<div class="double-divider"></div>')}
            <div class="card-overlay"><span class="card-cta">Enter Branch →</span></div>
          </div>
          <div class="card-info">
            <span class="card-branch">${b.name}</span>
            <h3 class="card-name" style="font-size:16px;">${b.masters.map(m => m.name).join(' & ')}</h3>
            <p class="card-location">📍 ${b.location}</p>
            <div class="card-border-line"></div>
            <p class="card-desc">${b.about}</p>
          </div>
        </div>`;
    } else {
      return `
        <div class="master-card" onclick="window.location='pages/${b.file}'" data-branch="${b.id}">
          <div class="card-glow"></div>
          <div class="card-img-wrap">
            <img src="images/${b.masters[0].image}" alt="${b.masters[0].name}" onerror="this.src='images/placeholder.jpg'" />
            <div class="card-overlay"><span class="card-cta">Enter Branch →</span></div>
          </div>
          <div class="card-info">
            <span class="card-branch">${b.name}</span>
            <h3 class="card-name">${b.masters[0].name}</h3>
            <p class="card-location">📍 ${b.location}</p>
            <div class="card-border-line"></div>
            <p class="card-desc">${b.about}</p>
          </div>
        </div>`;
    }
  }).join('');
  _attachTilt(grid, '.master-card');
}

/* ── Home page: student branches grid ─────────────────── */
function buildStudentGrid() {
  const section = document.getElementById('studentBranchesSection');
  const grid    = document.getElementById('studentGrid');
  if (!section || !grid) return;

  // Hide entire section if no student branches yet
  if (STUDENT_BRANCHES.length === 0) {
    section.style.display = 'none';
    return;
  }
  section.style.display = '';

  grid.innerHTML = STUDENT_BRANCHES.map(b => `
    <div class="student-card" onclick="window.location='pages/${b.file}'" data-branch="${b.id}">
      <div class="card-glow"></div>
      <div class="card-img-wrap">
        <img src="images/${b.masters[0].image}" alt="${b.masters[0].name}" onerror="this.src='images/placeholder.jpg'" />
        <div class="card-overlay"><span class="card-cta">Enter Branch →</span></div>
      </div>
      <div class="card-info">
        <div class="trained-under">Trained under <span>${b.trainedUnder || '—'}</span></div>
        <span class="card-branch">${b.name}</span>
        <h3 class="card-name">${b.masters[0].name}</h3>
        <p class="card-location">📍 ${b.location}</p>
        <div class="card-border-line"></div>
        <p class="card-desc">${b.about}</p>
      </div>
    </div>`).join('');
  _attachTilt(grid, '.student-card');
}

/* ── Shared tilt hover ─────────────────────────────────── */
function _attachTilt(grid, selector) {
  if (!window.matchMedia('(hover: hover)').matches) return;
  grid.querySelectorAll(selector).forEach(card => {
    card.addEventListener('mousemove', (e) => {
      const r = card.getBoundingClientRect();
      const x = ((e.clientX - r.left) / r.width  - 0.5) * 12;
      const y = ((e.clientY - r.top)  / r.height - 0.5) * 12;
      card.style.transform = `translateY(-8px) rotateX(${-y}deg) rotateY(${x}deg)`;
    });
    card.addEventListener('mouseleave', () => { card.style.transform = ''; });
  });
}

/* ── Gallery: load images via GitHub API ──────────────── */
/**
 * Reads the contents of images/gallery/ from your GitHub repo
 * and renders every image into #galleryGrid automatically.
 *
 * Set these two variables to match your repo:
 */
const GITHUB_USER = 'brandbuildR0720';
const GITHUB_REPO = 'Thekkan-Pore-Silamba-Kalai';
const GITHUB_BRANCH_NAME = 'main';   // usually 'main' or 'master'
const GALLERY_FOLDER = 'images/gallery';

async function loadGalleryFromGitHub() {
  const grid     = document.getElementById('galleryGrid');
  const emptyMsg = document.getElementById('galleryEmpty');
  const loader   = document.getElementById('galleryLoader');
  if (!grid) return;

  try {
    const apiUrl = `https://api.github.com/repos/${GITHUB_USER}/${GITHUB_REPO}/contents/${GALLERY_FOLDER}?ref=${GITHUB_BRANCH_NAME}`;
    const res  = await fetch(apiUrl);
    if (!res.ok) throw new Error('GitHub API error: ' + res.status);
    const files = await res.json();

    const images = files.filter(f =>
      f.type === 'file' && /\.(jpg|jpeg|png|webp|gif)$/i.test(f.name)
    );

    if (loader) loader.style.display = 'none';

    if (images.length === 0) {
      if (emptyMsg) emptyMsg.style.display = 'block';
      return;
    }

    // Remove existing static placeholder items
    grid.querySelectorAll('.gallery-item[data-static]').forEach(el => el.remove());

    images.forEach(img => {
      const item = document.createElement('div');
      item.className = 'gallery-item scroll-reveal';
      // data-cat can be set by filename prefix: e.g. "training_photo1.jpg" → cat=training
      const catMatch = img.name.match(/^([a-z]+)_/i);
      const cat = catMatch ? catMatch[1].toLowerCase() : 'general';
      item.dataset.cat = cat;
      item.innerHTML = `
        <img src="${img.download_url}" alt="${img.name}" loading="lazy"
             onerror="this.parentElement.style.display='none'"/>
        <div class="gallery-item-overlay"><span class="view-btn">🔍 View</span></div>`;
      item.querySelector('.view-btn').addEventListener('click', e => {
        e.stopPropagation();
        openLightbox(img.download_url);
      });
      item.querySelector('img').addEventListener('click', () => openLightbox(img.download_url));
      grid.appendChild(item);

      // trigger scroll-reveal
      setTimeout(() => item.classList.add('visible'), 30);
    });

    // Re-run filter if one is already active
    const activeFilter = document.querySelector('.filter-btn.active');
    if (activeFilter && activeFilter.dataset.filter !== 'all') {
      activeFilter.click();
    }

  } catch (err) {
    if (loader) loader.style.display = 'none';
    console.warn('Gallery load failed:', err);
    if (emptyMsg) {
      emptyMsg.textContent = 'Could not load gallery. Please try again later.';
      emptyMsg.style.display = 'block';
    }
  }
}
